### ISSUE TITLE
デプロイできない問題

### ISSUE THREAD

**Issue by technicakidz** [Takamura-000/my-first-blog#2]
### 概要
以下のデプロイの章で，PythonAnywhere 上の手順がうまくいかない．
https://tutorial.djangogirls.org/ja/deploy/

共有いただいたエラーメッセージ．
```
File "/home/tktk000/.local/bin/pa_autoconfigure_django.py", line 54, in <module>
nuke=arguments.get('--nuke')
File "/home/tktk000/.local/bin/pa_autoconfigure_django.py", line 32, in main
project.ensure_branch(branch),
File "/home/tktk000/.local/lib/python3.6/site-packages/pythonanywhere/django_project.py", line 32, in ensure_branch
"There are many branches in your repo. "
pythonanywhere.exceptions.SanityException: There are many branches in your repo. You need to specify which branch to use by adding --branch=<branch> option to
the command.
```

### ゴール

PythonAnywhere でデプロイまで完了し，インターネット上にアプリを公開できる．

###  補足
エラーがでしまったら以下の観点で書き出し状況を整理する．
- やりたかったこと
- 実際に試したこと
- 実行環境
- 結果(メッセージ全て)
- 実行後の挙動

**Comment by technicakidz** [comment]
:memo:

```
$ pa_autoconfigure_django.py https://github.com/[your-github-username]/my-first-blog.git --nuke
```

**Comment by Takamura-000** [comment]
19:46 ~ $ pa_autoconfigure_django.py https://github.com/Takamura-000/my-first-blog.git --nuke
< Running API sanity checks >
   \
    ~<:>>>>>>>>>
Cloning into '/home/tktk000/tktk000.pythonanywhere.com'...
remote: Enumerating objects: 22, done.
remote: Counting objects: 100% (22/22), done.
remote: Compressing objects: 100% (18/18), done.
remote: Total 22 (delta 0), reused 19 (delta 0), pack-reused 0
Unpacking objects: 100% (22/22), 4.85 KiB | 12.00 KiB/s, done.
Traceback (most recent call last):
  File "/home/tktk000/.local/bin/pa_autoconfigure_django.py", line 54, in <module>
    nuke=arguments.get('--nuke')
  File "/home/tktk000/.local/bin/pa_autoconfigure_django.py", line 32, in main
    project.ensure_branch(branch),
  File "/home/tktk000/.local/lib/python3.6/site-packages/pythonanywhere/django_project.py", line 32, in ensure_branch
    "There are many branches in your repo. "
pythonanywhere.exceptions.SanityException: There are many branches in your repo. You need to specify which branch to use by adding --branch=<branch> option to
 the command.

エラーがなくなりません。

**Comment by Takamura-000** [comment]
19:48 ~ $ ls
README.txt
lsコマンドでREADME.txtしか出てこないので、これがおかしいですよね？

**Comment by technicakidz** [comment]
そうですね。
アプリをGitHubリポジトリを介して仮想サーバ上に持ってくるコマンドなので、その状態は疑わしいです。
> lsコマンドでREADME.txtしか出てこないので、これがおかしいですよね？

自分の方でも調査を進めてみますね。

**Comment by technicakidz** [comment]
`--nuke` オプションでも実行が失敗した．このときの調査記事．

https://www.pythonanywhere.com/forums/topic/28426/

**Comment by Takamura-000** [comment]
本日実行したコマンドと結果
コマンド：`pip3.5 uninstall pythonanywhere`

結果：
```
DEPRECATION: Python 3.5 reached the end of its life on September 13th, 2020. Please upgrade your Python as Python 3.5 is no longer maintained. pip 21.0 will d
rop support for Python 3.5 in January 2021. pip 21.0 will remove support for this functionality.
WARNING: Skipping pythonanywhere as it is not installed.

```
コマンド：`pip3.6 install --user --upgrade --force-reinstall pythonanywhere`

結果：
```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following depen
dency conflicts.
tensorflow 2.4.0 requires six~=1.15.0, but you have six 1.16.0 which is incompatible.
tensorflow 2.4.0 requires typing-extensions~=3.7.4, but you have typing-extensions 4.1.1 which is incompatible.
fiona 1.8.18 requires click<8,>=4.0, but you have click 8.0.4 which is incompatible.
cligj 0.7.1 requires click<8,>=4.0, but you have click 8.0.4 which is incompatible.
argcomplete 1.12.2 requires importlib-metadata<4,>=0.23; python_version == "3.6", but you have importlib-metadata 4.8.3 which is incompatible.
```

**Comment by technicakidz** [comment]
以下のコマンドだといかがでしょうか．
コマンドにオプション `--branch=master` を追加しています．master ブランチを指定するような書き方なようです．
```
pa_autoconfigure_django.py https://github.com/Takamura-000/my-first-blog.git --nuke --branch=master
```

共有いただいた下記メッセージに着目しました．
> You need to specify which branch to use by adding --branch= option to the command.

メッセージを翻訳すると `--branch=` という実行コマンドのオプションがあると予測しました．

**Comment by Takamura-000** [comment]
実行したコマンド：
`pa_autoconfigure_django.py https://github.com/Takamura-000/my-first-blog.git --nuke --branch=master`

結果：
```

< Running API sanity checks >
   \
    ~<:>>>>>>>>>
Cloning into '/home/tktk000/tktk000.pythonanywhere.com'...
remote: Enumerating objects: 22, done.
remote: Counting objects: 100% (22/22), done.
remote: Compressing objects: 100% (18/18), done.
remote: Total 22 (delta 0), reused 19 (delta 0), pack-reused 0
Unpacking objects: 100% (22/22), 4.85 KiB | 15.00 KiB/s, done.
Already on 'master'
Your branch is up to date with 'origin/master'.
< Creating virtualenv with Python3.6 >
   \
    ~<:>>>>>>>>>
Removing tktk000.pythonanywhere.com...
Did not find environment /home/tktk000/.virtualenvs/tktk000.pythonanywhere.com to remove.
created virtual environment CPython3.6.13.final.0-64 in 8968ms
  creator CPython3Posix(dest=/home/tktk000/.virtualenvs/tktk000.pythonanywhere.com, clear=False, no_vcs_ignore=False, global=False)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/home/tktk000/.local/share/virtualenv)
    added seed packages: pip==21.1.2, setuptools==57.0.0, wheel==0.36.2
  activators BashActivator,CShellActivator,FishActivator,PowerShellActivator,PythonActivator,XonshActivator
virtualenvwrapper.user_scripts creating /home/tktk000/.virtualenvs/tktk000.pythonanywhere.com/bin/predeactivate
virtualenvwrapper.user_scripts creating /home/tktk000/.virtualenvs/tktk000.pythonanywhere.com/bin/postdeactivate
virtualenvwrapper.user_scripts creating /home/tktk000/.virtualenvs/tktk000.pythonanywhere.com/bin/preactivate
virtualenvwrapper.user_scripts creating /home/tktk000/.virtualenvs/tktk000.pythonanywhere.com/bin/postactivate
virtualenvwrapper.user_scripts creating /home/tktk000/.virtualenvs/tktk000.pythonanywhere.com/bin/get_env_details
  ___________________________________________________________________
/                                                                     \
| Pip installing -r                                                   |
| /home/tktk000/tktk000.pythonanywhere.com/requirements.txt (this may |
| take a couple of minutes)                                           |
\                                                                     /
  -------------------------------------------------------------------
   \
    ~<:>>>>>>>>>
Looking in links: /usr/share/pip-wheels
Collecting Django~=3.2.10
  Downloading Django-3.2.15-py3-none-any.whl (7.9 MB)
     |████████████████████████████████| 7.9 MB 17.2 MB/s 
Collecting pytz
  Downloading pytz-2022.1-py2.py3-none-any.whl (503 kB)
     |████████████████████████████████| 503 kB 21.4 MB/s 
Collecting asgiref<4,>=3.3.2
  Downloading asgiref-3.4.1-py3-none-any.whl (25 kB)
Collecting sqlparse>=0.2.2
  Downloading sqlparse-0.4.2-py3-none-any.whl (42 kB)
     |████████████████████████████████| 42 kB 176 kB/s 
Collecting typing-extensions
  Using cached typing_extensions-4.1.1-py3-none-any.whl (26 kB)
Installing collected packages: typing-extensions, sqlparse, pytz, asgiref, Django
Successfully installed Django-3.2.15 asgiref-3.4.1 pytz-2022.1 sqlparse-0.4.2 typing-extensions-4.1.1
< Creating web app via API >
   \
    ~<:>>>>>>>>>
< Adding static files mappings for /static/ and /media/ >
   \
    ~<:>>>>>>>>>
< Updating wsgi file at /var/www/tktk000_pythonanywhere_com_wsgi.py >
   \
    ~<:>>>>>>>>>
< Updating settings.py >
   \
    ~<:>>>>>>>>>
< Running collectstatic >
   \
    ~<:>>>>>>>>>
Traceback (most recent call last):
  File "/home/tktk000/tktk000.pythonanywhere.com/manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "/home/tktk000/.virtualenvs/tktk000.pythonanywhere.com/lib/python3.6/site-packages/django/core/management/__init__.py", line 419, in execute_from_comma
nd_line
    utility.execute()
  File "/home/tktk000/.virtualenvs/tktk000.pythonanywhere.com/lib/python3.6/site-packages/django/core/management/__init__.py", line 363, in execute
    settings.INSTALLED_APPS
  File "/home/tktk000/.virtualenvs/tktk000.pythonanywhere.com/lib/python3.6/site-packages/django/conf/__init__.py", line 82, in __getattr__
    self._setup(name)
  File "/home/tktk000/.virtualenvs/tktk000.pythonanywhere.com/lib/python3.6/site-packages/django/conf/__init__.py", line 69, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/tktk000/.virtualenvs/tktk000.pythonanywhere.com/lib/python3.6/site-packages/django/conf/__init__.py", line 170, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/local/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/tktk000/tktk000.pythonanywhere.com/mysite/settings.py", line 125, in <module>
    MEDIA_ROOT = Path(BASE_DIR / 'media')
NameError: name 'Path' is not defined
Traceback (most recent call last):
  File "/home/tktk000/.local/bin/pa_autoconfigure_django.py", line 54, in <module>
    nuke=arguments.get('--nuke')
  File "/home/tktk000/.local/bin/pa_autoconfigure_django.py", line 39, in main
    project.run_collectstatic()
  File "/home/tktk000/.local/lib/python3.6/site-packages/pythonanywhere/django_project.py", line 126, in run_collectstatic
    '--noinput',
  File "/usr/local/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/home/tktk000/.virtualenvs/tktk000.pythonanywhere.com/bin/python', '/home/tktk000/tktk000.pythonanywhere.com/manage.
py', 'collectstatic', '--noinput']' returned non-zero exit status 1.

```

**Comment by technicakidz** [comment]
以下エラーについて．
```
    MEDIA_ROOT = Path(BASE_DIR / 'media')
NameError: name 'Path' is not defined
```
調べたところ，下記の様に書き換える必要がありそうなことがわかった．
```
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
```
https://teratail.com/questions/346486

**Comment by technicakidz** [comment]
自分の環境で実施した結果も載せておきます．参考ください．

```
$ pa_autoconfigure_django.py https://github.com/technicakidz/djangogirls_pure.git --nuke --branch=master                                              

< Running API sanity checks >
   \
    ~<:>>>>>>>>>
Cloning into '/home/technicakidz/technicakidz.pythonanywhere.com'...
remote: Enumerating objects: 1044, done.
remote: Counting objects: 100% (1044/1044), done.
remote: Compressing objects: 100% (824/824), done.
remote: Total 1044 (delta 177), reused 1015 (delta 150), pack-reused 0
Receiving objects: 100% (1044/1044), 1.81 MiB | 0 bytes/s, done.
Resolving deltas: 100% (177/177), done.
Checking connectivity... done.
Already on 'master'
Your branch is up-to-date with 'origin/master'.

< Creating virtualenv with Python3.6 >
   \
    ~<:>>>>>>>>>
Removing technicakidz.pythonanywhere.com...
Did not find environment /home/technicakidz/.virtualenvs/technicakidz.pythonanywhere.com to remove.
Running virtualenv with interpreter /usr/local/bin/python3.6
Already using interpreter /usr/local/bin/python3.6
Using base prefix '/usr'
New python executable in /home/technicakidz/.virtualenvs/technicakidz.pythonanywhere.com/bin/python3.6
Also creating executable in /home/technicakidz/.virtualenvs/technicakidz.pythonanywhere.com/bin/python
Installing setuptools, pip, wheel...
done.
virtualenvwrapper.user_scripts creating /home/technicakidz/.virtualenvs/technicakidz.pythonanywhere.com/bin/predeactivate
virtualenvwrapper.user_scripts creating /home/technicakidz/.virtualenvs/technicakidz.pythonanywhere.com/bin/postdeactivate
virtualenvwrapper.user_scripts creating /home/technicakidz/.virtualenvs/technicakidz.pythonanywhere.com/bin/preactivate
virtualenvwrapper.user_scripts creating /home/technicakidz/.virtualenvs/technicakidz.pythonanywhere.com/bin/postactivate
virtualenvwrapper.user_scripts creating /home/technicakidz/.virtualenvs/technicakidz.pythonanywhere.com/bin/get_env_details

  ___________________________________________________________________
/                                                                     \
| Pip installing -r                                                   |
| /home/technicakidz/technicakidz.pythonanywhere.com/requirements.txt |
| (this may take a couple of minutes)                                 |
\                                                                     /
  -------------------------------------------------------------------
   \
    ~<:>>>>>>>>>
Looking in links: /usr/share/pip-wheels
Collecting Django~=2.2.4
  Using cached Django-2.2.28-py3-none-any.whl (7.5 MB)
Collecting pytz
  Using cached pytz-2022.1-py2.py3-none-any.whl (503 kB)
Collecting sqlparse>=0.2.2
  Using cached sqlparse-0.4.2-py3-none-any.whl (42 kB)
Installing collected packages: sqlparse, pytz, Django
Successfully installed Django-2.2.28 pytz-2022.1 sqlparse-0.4.2

< Creating web app via API >
   \
    ~<:>>>>>>>>>

< Adding static files mappings for /static/ and /media/ >
   \
    ~<:>>>>>>>>>

< Updating wsgi file at /var/www/technicakidz_pythonanywhere_com_wsgi.py >
   \
    ~<:>>>>>>>>>

< Updating settings.py >
   \
    ~<:>>>>>>>>>

< Running collectstatic >
   \
    ~<:>>>>>>>>>
Traceback (most recent call last):
  File "/home/technicakidz/.virtualenvs/technicakidz.pythonanywhere.com/lib/python3.6/site-packages/django/core/management/__init__.py", line 204, in fetch_co
mmand
    app_name = commands[subcommand]
KeyError: 'collectstatic'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/technicakidz/technicakidz.pythonanywhere.com/manage.py", line 21, in <module>
    main()
  File "/home/technicakidz/technicakidz.pythonanywhere.com/manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "/home/technicakidz/.virtualenvs/technicakidz.pythonanywhere.com/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_
from_command_line
    utility.execute()
  File "/home/technicakidz/.virtualenvs/technicakidz.pythonanywhere.com/lib/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/technicakidz/.virtualenvs/technicakidz.pythonanywhere.com/lib/python3.6/site-packages/django/core/management/__init__.py", line 211, in fetch_co
mmand
    settings.INSTALLED_APPS
  File "/home/technicakidz/.virtualenvs/technicakidz.pythonanywhere.com/lib/python3.6/site-packages/django/conf/__init__.py", line 79, in __getattr__
    self._setup(name)
  File "/home/technicakidz/.virtualenvs/technicakidz.pythonanywhere.com/lib/python3.6/site-packages/django/conf/__init__.py", line 66, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/technicakidz/.virtualenvs/technicakidz.pythonanywhere.com/lib/python3.6/site-packages/django/conf/__init__.py", line 176, in __init__
    raise ImproperlyConfigured("The SECRET_KEY setting must not be empty.")
django.core.exceptions.ImproperlyConfigured: The SECRET_KEY setting must not be empty.
Traceback (most recent call last):
  File "/home/technicakidz/.local/bin/pa_autoconfigure_django.py", line 54, in <module>
    nuke=arguments.get('--nuke')
  File "/home/technicakidz/.local/bin/pa_autoconfigure_django.py", line 39, in main
    project.run_collectstatic()
  File "/home/technicakidz/.local/lib/python3.6/site-packages/pythonanywhere/django_project.py", line 122, in run_collectstatic
    '--noinput',
  File "/usr/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/home/technicakidz/.virtualenvs/technicakidz.pythonanywhere.com/bin/python', '/home/technicakidz/technicakidz.python
anywhere.com/manage.py', 'collectstatic', '--noinput']' returned non-zero exit status 1.
```

**Comment by technicakidz** [comment]
Heroku 等別サーイスを検討することになったため，クローズします．
